# Generated by Django 4.2.5 on 2023-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityData',
        ),
    ]
