# Generated by Django 4.2.5 on 2023-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walert', '0002_delete_citydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertmsg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mintemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxtemp', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
